### ISSUE TITLE
Compatibility with base64 data URL ?

### ISSUE THREAD

**Issue by micabe** [bhoomika911/react-native-instagram-share-android#1]
Do we have this or should I make a PR..

Thanks

Mickael

**Comment by ershubhamgarg** [comment]
Hello @micabe , Whenever I trigger the function, it opens the Instagram app but it shows the toast : 'unable to load image'. And Instagram app closes.
Please help.

**Comment by micabe** [comment]
Hello @ershubhamgarg , Have a look at my fork https://github.com/micabe/react-native-share-instagram

It works for both android and ios
